import Navbar from '@/features/navbar'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}
        style={{
          backgroundColor: '#fff',
          // backgroundColor: '#0a1a2a',
          display:'flex',
          flexDirection:'column',
          overflowY:'auto',
        }}
      >
        <Navbar />
        {children}</body>
    </html>
  )
}
